### PR TITLE
Solution for No hint path defined

### PR DESCRIPTION
**Pull request by firatakandere**

### CODE REVIEW

**Comment by christian-thomas** [comment]
Hi @firatakandere, my fork was actually to make the package functional within L5, where as I presume you're using L4. I'd recommend using the base package https://github.com/davejamesmiller/laravel-breadcrumbs rather than my fork in that case.

**Comment by firatakandere** [comment]
I got this error on pure 5.0.2 version.

**Comment by christian-thomas** [comment]
In that case, you just need to change:

```
$this->loadViewsFrom($viewPath, 'breadcrumbs');
```

To:

```
$this->loadViewsFrom($viewPath, 'laravel-breadcrumbs');
```

The new namespace that the package developer is using though, is 'breadcrumbs'.

If you have a look at the `loadViewsFrom` function in the ServiceProvider class, that's got some additional validation round the `addNamespace` function.

**Comment by firatakandere** [comment]
Yes dude, that one works. Thanks!

**Pull request closed without merging**
